CREATE TABLE IF NOT EXISTS prices (
    id UUID PRIMARY KEY,
    gross DOUBLE PRECISION NOT NULL,
    net DOUBLE PRECISION NOT NULL,
    selling DOUBLE PRECISION NOT NULL,
    recommended DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
